#!/bin/sh

module="short"
device="short"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

insmod ./$module.ko $* || exit 1
major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

mknod /dev/short c $major 0

chgrp $group /dev/short
chmod $mode /dev/short
